### ISSUE TITLE
500 internal server error + Settings are not saved.

### ISSUE THREAD

**Issue by YorikGiesbers** [ilseh/RestfulCharging#12]
Hi,

I really like Oppleo so far! I got to the point that I got it working, but I am still experiencing some strange stuff.

- When I start a charging session I get a 500 internal server error
- When I try to save settings they are not saved and are 'blank' when I return to the settings page.

I looked in the Oppleo.log file and this is what I got from the 500 message:

> 2021-02-27 12:44:27,363 - Oppleo - 500 MainProcess - 1996196560 MainThread - ERROR - Exception on /start_charge_session/0002/ [GET]
Traceback (most recent call last):
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Oppleo/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Oppleo/src/nl/oppleo/webapp/flaskRoutes.py", line 80, in decorated
    return function(*args, **kwargs)
  File "/home/pi/Oppleo/src/nl/oppleo/webapp/flaskRoutes.py", line 545, in start_charge_session
    oppleoConfig.chThread.authorize(token)
AttributeError: 'NoneType' object has no attribute 'authorize'
2021-02-27 12:44:27,386 - nl.oppleo.webapp.flaskRoutes - 500 MainProcess - 1996196560 MainThread - DEBUG - 500 internal_server_error error handler

For the problem with the settings page I could not find any logging. When I look in the energy_device table I can see some settings, that I can't see in Oppleo itself.

energy_device table:
`# energy_device_id |  port_name   | slave_address | baudrate | bytesize | parity | stopbits | serial_timeout | debug | mode | close_port_after_each_call | modbus_timeout | modbus_config 
------------------+--------------+---------------+----------+----------+--------+----------+----------------+-------+------+----------------------------+----------------+---------------
 laadpaal_noord   | /dev/ttyUSB0 |             1 |    38400 |        8 | N      |        1 |              1 | t     | rtu  | f                          |              2 | SDM630v2
(1 row)`

![Schermafbeelding 2021-02-27 om 12 57 49](https://user-images.githubusercontent.com/55943842/109386524-76c9e780-78fb-11eb-95cd-4751cab50da6.png)

![Schermafbeelding 2021-02-27 om 13 02 43](https://user-images.githubusercontent.com/55943842/109386621-2010dd80-78fc-11eb-8c83-7c830473fab3.png)

in the meantime I got my Kwh meter working with the ModbusSDM630v2.py test script :) So it seems that I'm getting somewhere!

Thanks for your help!

**Comment by laemen** [comment]
One issue could be that when saving the settings the software compares the new value type with the type from the database. If the db field is not filled with some start value this comparison fails and the new value isn't saved. 
Also never tested changing the name (Naam laadpunt), as I haven't build a second one yet.

The db scripts run through liquibase when installing can miss default values, I haven't checked them all. So try to enter a starting value in the charger_config db table, you can probably figure out the field name.

My energy_device table looks similar, so I don't think the issue is here.
 energy_device_id |  port_name   | slave_address | baudrate | bytesize | parity | stopbits | serial_timeout | debug | mode | close_port_after_each_call | modbus_timeout | modbus_config 
------------------+--------------+---------------+----------+----------+--------+----------+----------------+-------+------+----------------------------+----------------+---------------
 laadpaal_noord   | /dev/ttyUSB0 |             1 |    38400 |        8 | N      |        1 |              1 | t     | rtu  | f                          |              2 | SDM630v2
(1 row)

I'm also making some changes just this last two weeks in the master branch, adding backup, which can lead to inconsistencies 😏.

**Comment by YorikGiesbers** [comment]
I filled up the charger_config table with some dummy values. But it does not seem to work. Fields in the 'instellingen' section remain empty and I can't save new values. Nothing to see on the logs :(


```
[ RECORD 1 ]-----------------------+-----------------------------------------------------
------------------------------------------------------------------------------------------
---------------------------------------------------------------------------
charger_name                        | laadpaal_noord
charger_tariff                      | 0.35
modified_at                         | 2021-02-26 20:36:26.59144
secret_key                          | abcdefghijklmnopqrstuvwxyz1234567890
wtf_csrf_secret_key                 | abcdefghijklmnopqrstuvwxyz1234567890
use_reloader                        | f
factor_whkm                         | 162
autosession_enabled                 | t
autosession_minutes                 | 90
autosession_energy                  | 0.1
autosession_condense_same_odometer  | t
pulseled_min                        | 3
pulseled_max                        | 98
gpio_mode                           | BCM
pin_led_red                         | 13
pin_led_green                       | 12
pin_led_blue                        | 16
pin_buzzer                          | 23
peakhours_offpeak_enabled           | f
peakhours_allow_peak_one_period     | f
pin_evse_switch                     | 5
pin_evse_led                        | 6
modbus_interval                     | 10
log_file                            | /tmp/Oppleo.log
webcharge_on_dashboard              | t
auth_webcharge                      | f
restrict_dashboard_access           | f
restrict_menu                       | f
allow_local_dashboard_access        | f
router_ip_address                   | 10.0.0.1
receipt_prefix                      | 00000
backup_enabled                      | f
backup_interval                     | d
backup_time_of_day                  | 08:00:00
backup_local_history                | 5
os_backup_enabled                   | f
os_backup_type                      | test
smb_backup_username                 | test
smb_backup_password                 | test
smb_backup_servername_or_ip_address | test
smb_backup_service_name             | test
smb_backup_remote_path              | test
backup_interval_weekday             | [false, false, false, false, false, false, false]
os_backup_history                   | 5
backup_interval_calday              | [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]
backup_success_timestamp            | 2015-08-07 05:00:01
```

update: just to make sure I'm getting you all the info, maybe this can help

Oppleo service log:

> oppleo.service - Oppleo Application
>    Loaded: loaded (/etc/systemd/system/Oppleo.service; enabled; vendor preset: enabled)
>    Active: active (running) since Sun 2021-02-28 20:17:19 CET; 1min 59s ago
>  Main PID: 503 (python3)
>     Tasks: 6 (limit: 2062)
>    CGroup: /system.slice/Oppleo.service
>            └─503 /home/pi/Oppleo/venv/bin/python3 /home/pi/Oppleo/src/nl/oppleo/webapp/Oppleo.py socketserver
> 
> Feb 28 20:17:33 laadpaal python3[503]: MinimalModbus debug mode. Clearing serial buffers for port /dev/ttyUSB0
> Feb 28 20:17:33 laadpaal python3[503]: MinimalModbus debug mode. No sleep required before write. Time since previous read: 3.12 ms, minimum silent period: 1.75 
> Feb 28 20:17:33 laadpaal python3[503]: MinimalModbus debug mode. Response from instrument: '\x01\x03\x02roÜÈ' (01 03 02 72 6F DC C8) (7 bytes), roundtrip time: 
> Feb 28 20:17:33 laadpaal python3[503]: 2021-02-28 20:17:33,195 - nl.oppleo.service.EvseReader - 503 MainProcess - 1940911200 EvseLedReaderThread - ERROR - Could
> Feb 28 20:17:33 laadpaal python3[503]: Traceback (most recent call last):
> Feb 28 20:17:33 laadpaal python3[503]:   File "/home/pi/Oppleo/src/nl/oppleo/services/EvseReader.py", line 49, in loop
> Feb 28 20:17:33 laadpaal python3[503]:     self.reader.loop(cb_until, cb_result)
> Feb 28 20:17:33 laadpaal python3[503]:   File "/home/pi/Oppleo/src/nl/oppleo/services/EvseReaderProd.py", line 106, in loop
> Feb 28 20:17:33 laadpaal python3[503]:     pigpio_pi = pigpio.pi()
> Feb 28 20:17:33 laadpaal python3[503]: NameError: name 'pigpio' is not defined

**Comment by YorikGiesbers** [comment]
Update:
I fixed the 500 internal server error btw, fiddled around a bit and I can start 'laadsessies' now. Only thing is that I still can't save new values in the settings section and when I start ModbusSDM630v2.py I can't see values being added to Oppleo.log. I also can't see gauges moving in Oppleo webapp. I do see readouts from the kwh meter in the terminal though

**Comment by laemen** [comment]
Finally caught up. Have a VM with Raspbian and installed Oppleo from fresh. Found quite some improvements :)

So the 500 error when starting the charge session is caused by the missing kWh meter. It triggers something in the thread reading from it, and there is no Thread started if there is not kWh meter, it misses this exception.
The kWh meter is really as the heart of Oppleo, so won't be able to start a session without one. If there is no kWh meter a simple button on the SmartEVSE would do. Anyway, you fixed it by actually adding a kWh meter :)

I do not have any issues updating settings though. Can you see if there is any error in your browser? What browser and version on what OS are you using?

**Comment by YorikGiesbers** [comment]
I'm using Chrome on Mac OS. When i'm saving a value it is not sending anything through an API or some sort. I also can't see values when I'm connecting through my Iphone.

This is the console log:
![Schermafbeelding 2021-03-01 om 12 07 35](https://user-images.githubusercontent.com/55943842/109489474-37300680-7a87-11eb-98ad-1e9964c4d944.png)


I fixed the pigpio error by installing pigpio on the venv.
When I look in Oppleo.log I'm seeing this message, maybe I have to add a dummy record in energy_device_measures?

>021-03-01 11:55:29,492 - nl.oppleo.daemon.EnergyDevice - 1692 MainProcess - 1949385824 KwhMeterReaderThread - DEBUG - handleIfTimeTo() - time to handle laadpaal_noord
2021-03-01 11:55:29,493 - nl.oppleo.daemon.EnergyDevice - 1692 MainProcess - 1949385824 KwhMeterReaderThread - DEBUG - Start measure laadpaal_noord
2021-03-01 11:55:29,493 - nl.oppleo.services.EnergyUtil - 1692 MainProcess - 1949385824 KwhMeterReaderThread - DEBUG - Production environment, getting real data
2021-03-01 11:55:29,828 - nl.oppleo.daemon.EnergyDevice - 1692 MainProcess - 1949385824 KwhMeterReaderThread - DEBUG - Measurement returned {'energy_device_id': 'laadpaal_noord', 'kwh_l1': 0.1, 'kwh_l2': 0.0, 'kwh_l3': 0.0, 'a_l1': 0.1, 'a_l2': 0.0, 'a_l3': 0.0, 'v_l1': 234.2, 'v_l2': 0.0, 'v_l3': 0.0, 'p_l1': 14.0, 'p_l2': 0.0, 'p_l3': 0.0, 'kw_total': 0.1, 'hz': 49.9}
2021-03-01 11:55:29,829 - nl.oppleo.daemon.EnergyDevice - 1692 MainProcess - 1949385824 KwhMeterReaderThread - DEBUG - New measurement values: None, 0.1, 2021-03-01 11:55:29.828901
2021-03-01 11:55:29,829 - nl.oppleo.models.EnergyDeviceMeasureModel - 1692 MainProcess - 1949385824 KwhMeterReaderThread - DEBUG - get_last_saved() energy_device_id laadpaal_noord 
2021-03-01 11:55:29,838 - nl.oppleo.daemon.EnergyDevice - 1692 MainProcess - 1949385824 KwhMeterReaderThread - DEBUG - Could not monitor energy device laadpaal_noord! list index out of range

**Comment by laemen** [comment]
Yes. looking at this now. It doesn't react proper to the empty table. For now add an entry manually.

insert into energy_device_measures (energy_device_id, kwh_l1, kwh_l2, kwh_l3, a_l1, a_l2, a_l3, v_l1, v_l2, v_l3, p_l1, p_l2, p_l3, kw_total, hz, created_at) values ('laadpaal_noord', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, CURRENT_TIMESTAMP);

**Comment by YorikGiesbers** [comment]
Great! im getting readings in the dashboard and also in verbruik. Still can't see values in instelling though.

**Comment by laemen** [comment]
Nice. How are your javascript debug skills?

The DevTools warnings are probably caused by Chrome plugins, I have those too, no issue there. I have a fix for the form-id warning, but also that should be no cause.

This 'in Startnull' seems strange? I have the initial status object. A shift-cmd R should do a reload and refreshes cache, maybe there is something stale. 

<img width="1166" alt="Schermafbeelding 2021-03-01 om 17 31 15" src="https://user-images.githubusercontent.com/36490484/109527469-fa2e3900-7ab3-11eb-8f3c-56f218a0e0c2.png">

To get the latest files do a `git pull` in the `/home/pi/Oppleo` directory, run `install/install.sh` and a `sudo systemctl restart Oppleo.service` to restart the software.

If you want to debug the javascript, in Sources after loading it calls `getSystemStatus()` which does a ajax call, so set a breakpoint on line 169 `console.log(result)` to check the success result, and on line 215 `if (result.status == 401) {` to check the result if the call fails.

**Comment by YorikGiesbers** [comment]
shift-cmd R didn't work. The Startnull was coming from a chrome plugin, I disabled it and the message was gone. The console message:

![Schermafbeelding 2021-03-01 om 21 52 00](https://user-images.githubusercontent.com/55943842/109557428-66229880-7ad8-11eb-8b64-e3a8005843f4.png)

I can edit the settings directly in the database, which is not ideal. But most of the settings are not meant to be changed daily.

**Comment by laemen** [comment]
Going into rabbit holes making quite some changes to get it working. Takes some time.

In the mean time, you seem to not have the latest version of Oppleo. There was an inbetween version comitted that has issues with the settings, you might have that version.

Run these commands on the pi to get the latest version:
- [ ] `cd /home/pi/Oppleo`
- [ ] `sudo systemctl stop Oppleo.service`
- [ ] `git pull`
- [ ] `install/install.sh`
- [ ] `sudo systemctl start Oppleo.service`
Then go to the web front and reload (shift-cmd R).

**Comment by YorikGiesbers** [comment]
Strange, when I do a git pull Oppleo gets corrupted.  Luckily I created a backup 👍  Any other way to get the newest files, or to check if I currently have the version which has settings issues?

**Comment by laemen** [comment]
What got corrupted?

Updates have changes in the database and in the application. They kind of go together. The install script uses liquibase which should not corrupt the database. Config files are local copies from examples and should not get overwritten. Sometimes a setting appears in the example and you have to add that to the local ini file, but if missing the app uses defaults and writes updates to the local file when you make changes in the web front.

So it really should not get corrupted. What error message are you seeing?

**Comment by YorikGiesbers** [comment]
I can't reach the webapp anymore and Oppleo.log is not adding new logging. so it looks like oppleo service is not doing anything. I'll investigate it a bit further when I have more time!. I booted from a backup, so it is working again. I can change settings in the database, for now that is fine :-) In the meantime I received RFID reader,LED and buzzer. I want to get that working as well. I'll keep you updated!

**Comment by YorikGiesbers** [comment]
I'm back :) Still was having issues with the git pull. I eventually had to put new parameters in my ini file (some where missing). Also the install.sh file was not updating my liquibase databases. Those two things prevented oppleo.service to run. I fixed those things

Now it is working again, and the settings can be seen and changed! 👍 
In the meantime I also got the buzzer, RFID reader, LED and EVSE switch working.

**Comment by laemen** [comment]
Nice, so it's working for you now?
I'm trying to make it more robust. Untill now I don't think anyone was really using Oppleo :) I'll make updates to a branch for now and merge when tested. There were some additions to the Oppleo.ini file in the src/nl/oppleo/config directory, however there should have been default values.
You can contact me directly on [WhatsApp](https://chat.whatsapp.com/CCyw1SSdEAFJ8wGtxLteaI)

**Comment by YorikGiesbers** [comment]
Yes, it is working now! thanks for your help so far 👍

**Comment by laemen** [comment]
On my known bugs list are some small issues:
- led has issues with colors. Maybe unused color pins are floating.
- noticed an rfid reader issue (stoped working). More testing.
- after a restart a backup is made (if enabled), even thouggh not due. Is the last success date properly restored from database?

**Comment by YorikGiesbers** [comment]
I'm noticing the LED error now. 

> 021-03-16 14:42:23,561 - nl.oppleo.services.LedLightProdHardware - 502 MainProcess - 1879045216 LedPulseThread - WARNING - init_gpio_pwm() - Could not initialize GPIO A PWM object already exists for this GPIO channel, retrying
init_gpio_pwm() - Could not initialize GPIO A PWM object already exists for this GPIO channel, retrying


I also can report a minor "bug" to add to your list:

- in the 'verbruik --> Table' section The volts at L2 are copied from L1. Since I only have a test setup now with L1 connected I noticed this. L2 should be 0.0V on my setup, but it is not

**Comment by laemen** [comment]
Noted.

**Comment by laemen** [comment]
Is it 0.0V in the database? ( `select v_l1, v_l2, v_l3 from energy_device_measures limit 20;` )

Trying to find out if the bug is in the data storing or presentation.

**Comment by YorikGiesbers** [comment]
Yes it is 0.0V in the DB so it is stored correctly

**Comment by laemen** [comment]
Thanks, found it. Never noticed it :)

**Comment by laemen** [comment]
Fixed. If you do a `git pull` you should get only that fix. Should also work through the webapp (Account-Beheer-Controleer op updates)
